name: Context and Variables Demo

on: workflow_dispatch

jobs:
    build-project:
      runs-on: ubuntu-latest
      steps:
      - uses: action/checkout@v4
      - name: Build solution
        run: dotnet build
          
        
